export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const FIREBASE_AUTH_STATECHANGED = "FIREBASE_AUTH_STATECHANGED";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED"

export const FETCH_JOBS ="FECTCH_JOBS";
export const FETCH_JOBS_FAILED ="FECTCH_JOBS_FAILED";
export const FETCH_JOBS_SUCCESS ="FECTCH_JOBS_SUCCESS";

